spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    driver-class-name: org.postgresql.Driver
    username: testuser
    password: testpassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
