spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gca_db
    username: gcauser
    password: gcapass
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: never
    prometheus:
      enabled: false
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO