spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    driver-class-name: org.postgresql.Driver
    username: testuser
    password: testpassword
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  liquibase:
    enabled: false
  jms:
    cache:
      enabled: false
    listener:
      auto-startup: false
  activemq:
    broker-url: tcp://localhost:61616
    user: gcauser
    password: gcapass

server:
  port: 8086

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO

security:
  password:
    length: 10