spring:
  application:
    name: service-working-hours
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://127.0.0.1:27017/working_hours}
      username: ${MONGO_USER:gcauser}
      password: ${MONGO_PASSWORD:gcapass}
  activemq:
    broker-url: ${BROKER_URL:tcp://localhost:61616}
    user: ${BROKER_USER}
    password: ${BROKER_PASSWORD}

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false

logging:
  level:
    org:
      hibernate: INFO
    root: WARN
  file:
    name: logs/service-working-hours-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %X{transactionId} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %X{transactionId} - %msg%n"
