openapi: 3.0.3
info:
  title: Trainer Workload API
  description: API for managing trainer workloads and calculating monthly training summaries.
  version: 1.0.0

servers:
  - url: http://localhost:8081/api/v1
    description: Local development environment

paths:
  /trainer/summary:
    post:
      summary: Manage trainer workload
      description: Accept trainer's workload data and perform the specified action (ADD/DELETE).
      operationId: modifyTrainerWorkload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainerWorkloadRequest'
      responses:
        '200':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainerWorkloadResponse'
    get:
      summary: Get trainer monthly training summary
      description: Retrieve the total training duration for the specified trainer, year, and month.
      operationId: getTrainerMonthlySummary
      parameters:
        - $ref: '#/components/parameters/TrainerUsername'
        - $ref: '#/components/parameters/Year'
        - $ref: '#/components/parameters/Month'
      responses:
        '200':
          description: Monthly training duration retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainerMonthlySummaryResponse'
        '400':
          description: Bad Request - The provided parameters are invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  parameters:
    TrainerUsername:
      name: username
      in: query
      required: true
      schema:
        type: string
      description: Trainer's username
      example: Ivan.Ivanoff

    Year:
      name: year
      in: query
      required: true
      schema:
        type: integer
        description: The year for which the summary is requested
        example: 2024

    Month:
      name: month
      in: query
      required: true
      schema:
        type: integer
        description: The month for which the summary is requested (1-12)
        example: 11

  schemas:
    TrainerWorkloadRequest:
      type: object
      properties:
        username:
          type: string
          description: Trainer's username
          example: Ivan.Ivanoff
        firstName:
          type: string
          description: Trainer's first name
          example: Ivan
        lastName:
          type: string
          description: Trainer's last name
          example: Ivanoff
        isActive:
          type: boolean
          description: Trainer's active status
          example: true
        trainingDate:
          type: string
          format: date
          description: Date of the training
          example: 2024-11-30
        trainingDuration:
          type: integer
          description: Duration of the training in minutes
          example: 90
        actionType:
          type: string
          enum: [ ADD, DELETE ]
          description: Action to perform on the workload
          example: ADD
      required:
        - username
        - firstName
        - lastName
        - isActive
        - trainingDate
        - trainingDuration
        - actionType

    TrainerWorkloadResponse:
      type: object
      properties:
        message:
          type: string
          description: Response message
          example: Workload updated successfully

    TrainerMonthlySummaryResponse:
      type: integer
      description: Total training duration for the specified month in minutes
      example: 720

    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          description: error code
          example: 67800
        error:
          type: string
          description: Error message
          example: "Invalid parameters: month must be between 1 and 12"
