spring:
  application:
    name: authentication-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true

server:
  port: 8083

application:
  server:
    url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
  file:
    name: logs/authentication-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %X{transactionId} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %X{transactionId} - %msg%n"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
