spring:
  application:
    name: eureka-service

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    root: WARN
    com:
      netflix:
        eureka: INFO
        discovery: INFO
  file:
    name: logs/eureka-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %X{transactionId} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %X{transactionId} - %msg%n"